---
development:
  cloud_name: nirazan-pokharel
  api_key: '333165192436847'
  api_secret: fbz55-IdhA_XtvpJZgAUwqEZ67U
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: nirazan-pokharel
  api_key: '333165192436847'
  api_secret: fbz55-IdhA_XtvpJZgAUwqEZ67U
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: nirazan-pokharel
  api_key: '333165192436847'
  api_secret: fbz55-IdhA_XtvpJZgAUwqEZ67U
  enhance_image_tag: true
  static_image_support: false
